In [12]:
#import numpy
import numpy as np

In [13]:
# Create a 3x3 matrix and a 1x3 vector
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([9,8,7])

# Broadcast the vector to a 3x3 matrix
broadcast1 = a + b
broadcast2 = a - b

print(broadcast1,"\n")
print(broadcast2)


[[10 10 10]
 [13 13 13]
 [16 16 16]] 

[[-8 -6 -4]
 [-5 -3 -1]
 [-2  0  2]]


In broadcasting, the smaller array is strectched and duplicating filling the extra space with 0 so that all the matrices involved in the operation are of same size so the operations can be conducted element wise.
It results in mathematical operation between arrays of different sizes.
Here in the code above matrix a is of *3x3* and matrix b is of size *1x3*, in broadcasting matrix b is strechted so that the element wise operations are conducted.